# Generated by Django 2.2 on 2019-04-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=170)),
                ('food_name', models.CharField(max_length=170)),
                ('DateTaker', models.DateField(blank=True, null=True)),
                ('TimeTaker', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
