# Generated by Django 2.2 on 2019-04-19 05:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_fooddetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooddetails',
            name='details',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
