# Generated by Django 2.2 on 2019-04-19 05:58

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190419_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooddetails',
            name='image',
        ),
        migrations.AlterField(
            model_name='fooddetails',
            name='details',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
