# Generated by Django 2.2 on 2019-04-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190419_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulelist',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
