# Generated by Django 2.2 on 2019-04-23 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_schedulelist_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulelist',
            name='file',
        ),
        migrations.AddField(
            model_name='fooddetails',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
